name: VCMI-HD-Converter

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pyinstaller-win:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'VCMI-HD-Converter'
          options: --onefile, --name "VCMI-HD-Converter", --windowed, 
